feat: Add Meson as a build option
AccessKit/accesskit-c pull request #2
Opened 2024-06-30 21:08 UTC by mwcampbell

This can coexist with the current CMake build system. I don't know yet if we want to keep the current CMake build system around in the long term or switch completely to Meson. AccessKit doesn't yet actually support any targets that Meson doesn't support, but that may change when we implement the Android backend in the next few months.

I'm making this a draft because this branch is currently based on the standalone-repo branch, which isn't merged. When that branch is merged, I can rebase this branch and take this PR out of draft status.

This PR is derived from librsvg's Meson build system, and most of the original files didn't have a copyright or license header. librsvg is under the LGPL. So my interpretation is that in the worst case, this means that accesskit-c is under the LGPL when built with Meson, but not when built with CMake or directly with cargo. But I would like clarification on that from @amyspark, who did most of the Meson work for librsvg. Once that's clarified, I'll add some kind of attribution and copyright header to these files.

2024-06-30 21:12 UTC, mwcampbell commented
One notable change compared to librsvg: I decided not to use cargo-c. Since Meson is building the shared library and .pc file, and installing all of the artifacts, I concluded that cargo-c wasn't accomplishing anything that cargo itself couldn't do.

2024-07-01 13:11 UTC, amyspark commented
Hi! I can confirm that if you got my scaffold from librsvg, it's licensed under LGPL-2.1. Feel free to credit and adjust it as needed :+1:

(edited for legal consistency)

2024-07-01 13:15 UTC, mwcampbell commented
Thanks @amyspark. What I meant to ask, though, is whether this means that the LGPL applies to our library itself when built with Meson. I'm sorry I wasn't clear about that.

2024-07-01 13:25 UTC, amyspark commented
@mwcampbell as I understand it (and from my POV as author of those files) the LGPL only applies to **my files** and changes you make to them e.g. extending the `makedef` script.

You're free to release accesskit-c under the license that suits you best and I have no intentions to encumber that choice.

2024-07-01 13:28 UTC, mwcampbell commented
@amyspark Thank you. I'll add a copyright and license notice.

2024-07-01 13:37 UTC, mwcampbell commented
@amyspark Is it under the LGPL 3.0 or 2.1? I only see LGPL 2.1 in librsvg. I hate to nit-pick, but I want to make sure I get this right. Thanks.

2024-07-01 14:00 UTC, amyspark commented
@mwcampbell `LGPL-2.1-or-later` for all. I've fixed the comment I made earlier to be absolutely clear.

I got confused for a moment since one file (`makedef.py`) comes originally from another repo of ours: https://gitlab.freedesktop.org/gstreamer/meson-ports/ffmpeg/-/blob/a5bc5338f300324028b7051d4b280a7ccef67d64/compat/windows/makedef.py

2024-07-30 13:27 UTC, mwcampbell commented
I forgot that this PR was still a draft. I also forgot to rebase it before taking it out of draft status. Done now.

2024-09-08 17:36 UTC, DataTriny commented
I am seeing the following warnings when setting up the project on Windows:

```
meson.build:349: DEPRECATION: Project uses feature that was always broken, and is now deprecated since '1.3.0': str.format: Value other than strings, integers, bools, options, dictionaries and lists thereof..
...
meson.build:394: WARNING: Project targets '>= 1.2.0' but uses feature introduced in '1.3.0': "shared_library" keyword argument "vs_module_defs" of type CustomTargetIndex.
...
WARNING: Project specifies a minimum meson_version '>= 1.2.0' but uses features which were added in newer versions:
 * 1.3.0: {'"shared_library" keyword argument "vs_module_defs" of type CustomTargetIndex'}
WARNING: Broken features used:
 * 1.3.0: {'str.format: Value other than strings, integers, bools, options, dictionaries and lists thereof.'}
```

Unless we have no way around, it would be better to fix these right now.

I encounter errors when linking so I can't tell if this is fully working at the moment, need to investigate more.

2024-11-20 17:21 UTC, lu-zero commented
I noticed that you have a branch that adds the cargo-c metadata, did you have any problem with using it? If not could you also add it so distributions that prefer cargo-c can use it as well?

2024-11-24 14:37 UTC, mwcampbell commented
I abandoned cargo-c in favor of Meson because the latter was necessary to meet GTK's needs. But I guess adding cargo-c as a third option wouldn't add much maintenance in the long term.

2024-11-24 16:44 UTC, mwcampbell commented
OK, I think I've got this fully working on all three major platforms, including both MSVC and MSYS2 on Windows.

@amyspark I'd also appreciate your review, since this is based on your scripts for librsvg.

2024-12-15 15:19 UTC, DataTriny requested changes

2024-12-15 15:19 UTC, DataTriny commented on meson.build
> +msrv = '1.70.0'
```suggestion
msrv = '1.75.0'
```

2024-12-15 17:07 UTC, DataTriny approved these changes

2024-12-15 17:09 UTC, merged